### ISSUE TITLE
improve launcher UI

### ISSUE THREAD

**Issue by frickinfire** [frickinfire/VanillaLauncher#11]
it looks really bad right now, need to get to this eventually

**Comment by playervalley** [comment]
> maybe after alpha 0.7?

not much different as of 0.9.1, might close this but having doubts

**Comment by frickinfire** [comment]
> > maybe after alpha 0.7?
> 
> not much different as of 0.9.1, might close this but having doubts

🤷‍♂️ its a forever WIP

**Comment by frickinfire** [comment]
@ethanmcd2502 seems to have this done
